[package]
name = "cairo-native-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-native = { git = "https://github.com/lambdaclass/cairo_native.git" }
cairo-felt = "0.8.2"
